# Generated by Django 4.1.1 on 2022-09-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passenger_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.passenger'),
        ),
    ]
