# Generated by Django 4.1.1 on 2022-09-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ride_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='passengers',
        ),
        migrations.AddField(
            model_name='passenger',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ride'),
        ),
    ]
