# Generated by Django 4.1.1 on 2022-09-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ride_passengers_passenger_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='api.ride'),
        ),
    ]
