# Generated by Django 4.1.1 on 2022-09-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ride_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
