# Generated by Django 4.1.1 on 2022-09-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ride_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='current_capacity',
        ),
    ]
